// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Nonae.Tests.EndToEnd
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Options")]
    public partial class OptionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Options.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Options", "In order to know what requests I can make\r\nAs a consumer of the API\r\nI want to be" +
                    " make OPTIONS calls", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Call OPTIONS on an endpoint")]
        [NUnit.Framework.TestCaseAttribute("a collection", "told", "POST", null)]
        [NUnit.Framework.TestCaseAttribute("a collection", "told", "GET", null)]
        [NUnit.Framework.TestCaseAttribute("a collection", "told", "HEAD", null)]
        [NUnit.Framework.TestCaseAttribute("a collection", "not told", "DELETE", null)]
        [NUnit.Framework.TestCaseAttribute("a collection", "not told", "PUT", null)]
        [NUnit.Framework.TestCaseAttribute("a single resource", "told", "GET", null)]
        [NUnit.Framework.TestCaseAttribute("a single resource", "told", "PUT", null)]
        [NUnit.Framework.TestCaseAttribute("a single resource", "told", "HEAD", null)]
        [NUnit.Framework.TestCaseAttribute("a single resource", "told", "DELETE", null)]
        [NUnit.Framework.TestCaseAttribute("a single resource", "not told", "POST", null)]
        [NUnit.Framework.TestCaseAttribute("the root", "told", "GET", null)]
        [NUnit.Framework.TestCaseAttribute("the root", "told", "HEAD", null)]
        [NUnit.Framework.TestCaseAttribute("the root", "not told", "DELETE", null)]
        [NUnit.Framework.TestCaseAttribute("the root", "not told", "PUT", null)]
        [NUnit.Framework.TestCaseAttribute("the root", "not told", "POST", null)]
        [NUnit.Framework.TestCaseAttribute("a silly url", "not told", "DELETE", null)]
        [NUnit.Framework.TestCaseAttribute("a silly url", "not told", "GET", null)]
        [NUnit.Framework.TestCaseAttribute("a silly url", "not told", "HEAD", null)]
        [NUnit.Framework.TestCaseAttribute("a silly url", "not told", "PUT", null)]
        [NUnit.Framework.TestCaseAttribute("a silly url", "not told", "POST", null)]
        public virtual void CallOPTIONSOnAnEndpoint(string endpoint, string status, string verb, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Call OPTIONS on an endpoint", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.When(string.Format("I call OPTIONS on {0}", endpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("I get a 200 OK response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.And(string.Format("I am {0} I can {1}", status, verb), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
